name: Docker Publish

on:
  push:
    branches:
      - main  # Replace with your main branch name
  workflow_dispatch:      

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --tag "${{ secrets.DOCKERHUB_USERNAME }}"/kubernetes-toolbox:latest --push .
        env:
          DOCKER_CLI_ACI: 1
        working-directory: ./  # Replace with the actual path

